buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.6.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.25"
        // ✅ KSP for Room
        classpath "com.google.devtools.ksp:symbol-processing-gradle-plugin:1.9.25-1.0.20"
        classpath 'com.google.gms:google-services:4.4.2'

    }
}

tasks.register("clean", Delete) {
    delete(rootProject.buildDir)
}
